GPMSA normalization options for output data
libqueso/queso pull request #602
Opened 2017-06-14 14:57 UTC by roystgnr

This adds analogous scaling options to what we support for the input data, implements output autoscaling calculations within GPMSAOptions, and implements output scaling within GPMSA.

The "autoscale-all" regression test results changed, as expected, which unfortunately does not necessarily prove the results changed as expected.

2017-06-14 19:31 UTC, briadam requested changes
Change might not strictly be needed, but comments should be reviewed before merge.

2017-06-14 19:31 UTC, briadam commented on src/gp/inc/GPMSAOptions.h
> +  void set_autoscale_minmax_output(unsigned int i);
Good to have this for completeness, though Brian Williams recommends always using mean/variance scaling.

2017-06-14 19:31 UTC, briadam commented on src/gp/inc/GPMSAOptions.h
> +  void set_autoscale_meanvar_output(unsigned int i);
As we think forward to the functional case, probably don't need scaling on a per-component basis.  More likely on a per-group basis, but having this generality is fine.

2017-06-14 19:31 UTC, briadam commented on src/gp/src/GPMSA.C
> +      // more normalization to do?
I'm a little surprised that we don't have to scale the experiment covariance information provided by the user, as we did in examples/gp/linear_verif/  Or maybe you are with Wy above...

2017-06-14 19:31 UTC, briadam commented on src/gp/src/GPMSAOptions.C
> +                ((m_outputScaleMin[p] != 0) ||
Potentially dangerous test for floating point equality.

2017-06-14 19:31 UTC, briadam commented on src/gp/src/GPMSAOptions.C
> +                ((m_outputScaleMin[p] != 0) ||
Potentially dangerous test for floating point equality.

2017-06-14 19:31 UTC, briadam commented on src/gp/src/GPMSA.C
> +      (*simulationOutputMeans)[j] +=
Verify that this isn't doubly applying the mean shift between the code here and in normalized_output.

2017-06-14 19:31 UTC, briadam commented on src/gp/src/GPMSA.C
> +        (*simulationOutputMeans)[j];
Verify that this isn't doubly applying the mean shift between the code here and in normalized_output.  (And in all places normalized_output is being called below.)

2017-06-14 19:31 UTC, briadam commented on src/gp/src/GPMSA.C
> +              Wy(i,j) = W_i(outi,outj) *
Perhaps this is accounting for the need to scale the user's observation covariance?

2017-06-14 19:43 UTC, roystgnr commented on src/gp/inc/GPMSAOptions.h
> +  void set_autoscale_meanvar_output(unsigned int i);
Yeah; I think when we add the partitioning capability, this won't be "output i" but rather "output subpartition i".

2017-06-14 19:47 UTC, roystgnr commented on src/gp/src/GPMSA.C
> +      (*simulationOutputMeans)[j] +=
This code is correct, but it's subtle.  If you're doing mean/variance normalization on a single index i, then simulationOutputMeans will be 0, and calculating it is a waste of time, but still gives the correct result.

But, if you're normalizing based on min/max, or a user-submitted range, or if index i is only one index of many in a partition, then the mean of the normalized values will not be zero, and yet we'll still want to subtract it off before doing the SVD.

2017-06-14 19:48 UTC, roystgnr commented on src/gp/src/GPMSA.C
> +              Wy(i,j) = W_i(outi,outj) *
This was a bug, fixed in the latest commit; thanks.

2017-06-14 19:48 UTC, roystgnr commented on src/gp/src/GPMSA.C
> +      // more normalization to do?
I was scaling it, but in the *wrong* direction, before that fix.

2017-06-14 19:59 UTC, roystgnr commented on src/gp/src/GPMSAOptions.C
> +                ((m_outputScaleMin[p] != 0) ||
Nah.  The fill in set_output_scaling is with *exactly* 0 and 1, so we can rely on an exact test to tell us if something other than a fill happened.

Now, there is a loophole here: if someone manually sets 0 and 1, then requests automatic scaling, then we won't catch that and scream at them - by doing something insane *twice* they'll have evaded our sanity check...

2017-06-28 16:27 UTC, briadam approved these changes

2017-06-28 18:28 UTC, merged